enum SearchFilter{
  colorWhite,colorBlue,colorBlack,colorRed,colorGreen,colorColorless,colorMulti,
  rarityCommon,rarityUncommon,rarityRare,rarityMythic,
  typeCreature,typePlaneswalker,typeInstant,typeSorcery,typeEnchantment,typeArtifact,typeLand,typeBattle,
  manaValue0,manaValue1,manaValue2,manaValue3,manaValue4,manaValue5,manaValue6,manaValue7AndMore,
  setMul,setMom,setOne,setBrr,setBro,setDmu,
  setSnc,setNeo,setVow,setMid,
  setAfr,setStx,setKhm,setZnr,
  setM21,setIko,setThb,setEld,
  setM20,setWar,setRna,setGrn,
  setM19,setDom,setRix,setXln,
  setHou,setAkh,setAer,setKld,
  setEmn,setSoi,setOgw,setBfz,
  setOri,setDtk,setFrf,setKtk,
  setM15,setJou,setBng,setThs,
  setM14,setDgm,setGtc,setRtr,

  setYone,setYbro,setYdmu,
  setHbg,setYSnc,setYNeo,setYMid,
}